# Site settings
title: Xiaozhe Yao
email: 
description: Machine Vision
baseurl: ""
url: "https://xzyaoi.github.io"
github_username:  stevefermi

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap